import { useMemo } from "react";
import createSceneLoader from "../services/sceneLoader";

export default function useSceneLoader(deps) {
  return useMemo(
    () =>
      createSceneLoader({
        snap: deps.snap,
        packPadding: deps.packPadding,
        packMarginX: deps.packMarginX,
        packMarginY: deps.packMarginY,
        drawScale: deps.drawScale,
        packGrid: deps.packGrid,
        packAngle: deps.packAngle,
        packMode: deps.packMode,
        setError: deps.setError,
        setAutoFit: deps.setAutoFit,
        setSceneLoading: deps.setSceneLoading,
        setSvgSize: deps.setSvgSize,
        setOverlayItems: deps.setOverlayItems,
        setSelectedOverlayId: deps.setSelectedOverlayId,
        setSvgFallback: deps.setSvgFallback,
        setBorderSegments: deps.setBorderSegments,
        setRawSegments: deps.setRawSegments,
        setNodes: deps.setNodes,
        setSegs: deps.setSegs,
        setScene: deps.setScene,
        setZoneScene: deps.setZoneScene,
        setDrawScale: deps.setDrawScale,
        setLabels: deps.setLabels,
        setPackedImageSrc: deps.setPackedImageSrc,
        setPackedImageSrc2: deps.setPackedImageSrc2,
        setPackedLabels: deps.setPackedLabels,
        setScale: deps.setScale,
        setPos: deps.setPos,
        setRegionScale: deps.setRegionScale,
        setRegionPos: deps.setRegionPos,
        setRegion2Scale: deps.setRegion2Scale,
        setRegion2Pos: deps.setRegion2Pos,
        setZoneScale: deps.setZoneScale,
        setZonePos: deps.setZonePos,
        stageSize: deps.stageSize,
        fitRegionToView: deps.fitRegionToView,
        fitRegion2ToView: deps.fitRegion2ToView,
        fitZoneToView: deps.fitZoneToView,
      }),
    [
      deps.snap,
      deps.packPadding,
      deps.packMarginX,
      deps.packMarginY,
      deps.drawScale,
      deps.packGrid,
      deps.packAngle,
      deps.packMode,
      deps.setError,
      deps.setAutoFit,
      deps.setSceneLoading,
      deps.setSvgSize,
      deps.setOverlayItems,
      deps.setSelectedOverlayId,
      deps.setSvgFallback,
      deps.setBorderSegments,
      deps.setRawSegments,
      deps.setNodes,
      deps.setSegs,
      deps.setScene,
      deps.setZoneScene,
      deps.setDrawScale,
      deps.setLabels,
      deps.setPackedImageSrc,
      deps.setPackedImageSrc2,
      deps.setPackedLabels,
      deps.setScale,
      deps.setPos,
      deps.setRegionScale,
      deps.setRegionPos,
      deps.setRegion2Scale,
      deps.setRegion2Pos,
      deps.setZoneScale,
      deps.setZonePos,
      deps.stageSize,
      deps.fitRegionToView,
      deps.fitRegion2ToView,
      deps.fitZoneToView,
    ]
  );
}
