import ExportModal from "./ExportModal";
import PackedPanel from "./PackedPanel";
import RegionPanel from "./RegionPanel";
import SimModal from "./SimModal";
import SourcePanel from "./SourcePanel";
import TopBar from "./TopBar";
import ZonePanel from "./ZonePanel";

export default function AppLayout(props) {
  const {
    sceneState,
    packState,
    overlayState,
    editState,
    viewState,
    simState,
    sceneLoader,
    overlayHandlers,
    sourceHandlers,
    exporter,
    simHandlers,
    wheelHandlers,
    nodeLayer,
    borderLayer,
    simStage,
    saveSvg,
    saveState,
    findZoneAtPoint,
    mergeNodesIfClose,
    measureText,
    toPoints,
    transformPath,
    offsetPoints,
    transformOverlayToPacked,
  } = props;

  return (
    <div className="app">
      <div className="content">
        <div className="column-left">
          <TopBar
            loadScene={sceneLoader.loadScene}
            exportPdf={exporter.exportPdf}
            setSimProgress={simState.setSimProgress}
            setSimPlaying={simState.setSimPlaying}
            setShowSim={simState.setShowSim}
            exportMsg={sceneState.exportMsg}
            error={sceneState.error}
          />
          <SourcePanel
            sceneLoading={sceneState.sceneLoading}
            leftRef={viewState.leftRef}
            scene={sceneState.scene}
            edgeMode={editState.edgeMode}
            addNodeMode={editState.addNodeMode}
            deleteEdgeMode={editState.deleteEdgeMode}
            setEdgeMode={editState.setEdgeMode}
            setAddNodeMode={editState.setAddNodeMode}
            setDeleteEdgeMode={editState.setDeleteEdgeMode}
            setEdgeCandidate={editState.setEdgeCandidate}
            setDeleteEdgeCandidate={editState.setDeleteEdgeCandidate}
            handleOverlayPick={overlayHandlers.handleOverlayPick}
            overlayInputRef={overlayState.overlayInputRef}
            handleOverlayFileChange={overlayHandlers.handleOverlayFileChange}
            overlayFill={overlayState.overlayFill}
            setOverlayFill={overlayState.setOverlayFill}
            selectedOverlayId={overlayState.selectedOverlayId}
            updateOverlayColor={overlayHandlers.updateOverlayColor}
            downloadStage={exporter.downloadStage}
            stageRef={viewState.stageRef}
            stageSize={viewState.stageSize}
            scale={viewState.scale}
            pos={viewState.pos}
            handleWheel={wheelHandlers.handleWheel}
            onMouseMove={sourceHandlers.handleSourceMouseMove}
            onMouseLeave={sourceHandlers.handleSourceMouseLeave}
            onMouseDown={sourceHandlers.handleSourceMouseDown}
            edgeCandidate={editState.edgeCandidate}
            deleteEdgeCandidate={editState.deleteEdgeCandidate}
            setSegs={sceneState.setSegs}
            segs={sceneState.segs}
            nodes={sceneState.nodes}
            setNodes={sceneState.setNodes}
            overlayItems={overlayState.overlayItems}
            setSelectedOverlayId={overlayState.setSelectedOverlayId}
            findZoneAtPoint={findZoneAtPoint}
            overlayNodeRefs={overlayState.overlayNodeRefs}
            overlayTransformerRef={overlayState.overlayTransformerRef}
            setOverlayItems={overlayState.setOverlayItems}
            nodeLayer={nodeLayer}
            borderLayer={borderLayer}
            mergeNodesIfClose={mergeNodesIfClose}
            snap={sceneState.snap}
          />
        </div>
        <div className="right">
          <PackedPanel
            scene={sceneState.scene}
            sceneLoading={sceneState.sceneLoading}
            regionWrapRef={viewState.regionWrapRef}
            regionRef={viewState.regionRef}
            regionScale={viewState.regionScale}
            regionPos={viewState.regionPos}
            regionStageSize={viewState.regionStageSize}
            handleRegionWheel={wheelHandlers.handleRegionWheel}
            showImages={sceneState.showImages}
            setShowImages={sceneState.setShowImages}
            showStroke={sceneState.showStroke}
            setShowStroke={sceneState.setShowStroke}
            showLabels={sceneState.showLabels}
            setShowLabels={sceneState.setShowLabels}
            labelFontFamily={sceneState.labelFontFamily}
            setLabelFontFamily={sceneState.setLabelFontFamily}
            labelFontSize={sceneState.labelFontSize}
            setLabelFontSize={sceneState.setLabelFontSize}
            downloadStage={exporter.downloadStage}
            packedFillPaths={packState.packedFillPaths}
            packedBleedPaths={packState.packedBleedPaths}
            packedFillPaths2={packState.packedFillPaths2}
            packedBleedPaths2={packState.packedBleedPaths2}
            packedBleedError={packState.packedBleedError}
            packedBleedError2={packState.packedBleedError2}
            overlayItems={overlayState.overlayItems}
            transformOverlayToPacked={transformOverlayToPacked}
            selectedZoneId={sceneState.selectedZoneId}
            setSelectedZoneId={sceneState.setSelectedZoneId}
            packedLabels={sceneState.packedLabels}
            setPackedLabels={sceneState.setPackedLabels}
            measureText={measureText}
            toPoints={toPoints}
            transformPath={transformPath}
            offsetPoints={offsetPoints}
          />
          <div className="preview-row">
            <RegionPanel
              scene={sceneState.scene}
              sceneLoading={sceneState.sceneLoading}
              region2WrapRef={viewState.region2WrapRef}
              region2Ref={viewState.region2Ref}
              region2Scale={viewState.region2Scale}
              region2Pos={viewState.region2Pos}
              region2StageSize={viewState.region2StageSize}
              handleRegion2Wheel={wheelHandlers.handleRegion2Wheel}
              saveSvg={saveSvg}
              saveState={saveState}
              loadScene={sceneLoader.loadScene}
              nodes={sceneState.nodes}
              segs={sceneState.segs}
              overlayItems={overlayState.overlayItems}
              downloadStage={exporter.downloadStage}
              toPoints={toPoints}
            />
            <ZonePanel
              zoneWrapRef={viewState.zoneWrapRef}
              zoneRef={viewState.zoneRef}
              zoneScene={sceneState.zoneScene}
              scene={sceneState.scene}
              sceneLoading={sceneState.sceneLoading}
              zoneStageSize={viewState.zoneStageSize}
              zoneScale={viewState.zoneScale}
              zonePos={viewState.zonePos}
              handleZoneWheel={wheelHandlers.handleZoneWheel}
              showImages={sceneState.showImages}
              showLabels={sceneState.showLabels}
              selectedZoneId={sceneState.selectedZoneId}
              setSelectedZoneId={sceneState.setSelectedZoneId}
              labelFontFamily={sceneState.labelFontFamily}
              labelFontSize={sceneState.labelFontSize}
              overlayItems={overlayState.overlayItems}
              loadScene={sceneLoader.loadScene}
              downloadStage={exporter.downloadStage}
              toPoints={toPoints}
              measureText={measureText}
            />
          </div>
        </div>
      </div>
      <ExportModal
        exportPdfLoading={sceneState.exportPdfLoading}
        exportPdfInfo={sceneState.exportPdfInfo}
        exportHtmlInfo={sceneState.exportHtmlInfo}
        setExportPdfInfo={sceneState.setExportPdfInfo}
      />
      <SimModal
        showSim={simState.showSim}
        setShowSim={simState.setShowSim}
        simActiveLabel={simState.simActiveLabel}
        simStage={simStage}
        simProgress={simState.simProgress}
        setSimProgress={simState.setSimProgress}
        simPlaying={simState.simPlaying}
        handleSimPlayToggle={simHandlers.handleSimPlayToggle}
        handleSimVideoDownload={simHandlers.handleSimVideoDownload}
        simVideoLoading={simState.simVideoLoading}
        simWrapRef={simState.simWrapRef}
      />
    </div>
  );
}
